# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ixrvcKezlZSlVgT3VSP9-h58YcInoaSq
"""

import sklearn
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
# from sklearn import metrics
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from google.colab import files 



#B
upload = files.upload()
dataset = pd.read_csv("KO.csv")
print(dataset)



#C 
dataset.isnull()
print(dataset.isnull().sum()/ len(dataset))


#D 
#E

#F

    # date vs low
date = dataset['Date']
low = dataset['Low']
print(plt.plot(date,low))

    #Date vs  High

date = dataset["Date"]
high = dataset["High"]
print(plt.plot(date,high))


    #Date vs Close
date = dataset["Date"]
close = dataset["Close"]
print(plt.plot(date,close))



#G 
x_variable = ['Volume','Low','High' ]
y_variable = ["Close"]


x = dataset[x_variable].values.reshape(-1,3)
y = dataset[y_variable].values.reshape(-1,1)
x_train, x_test, y_train, y_test =  train_test_split(x, y, test_size = 0.2) #20% for testing , 80% for building


print(x_train.shape)
print(x_test.shape)

multiple_reg = LinearRegression()
model = multiple_reg.fit(x_train, y_train)

#H
x_predict = np.array([17.70, 59.01, 60.88]) 
x_predict = x_predict.reshape(1,-3)
y_predict = model.predict(x_predict)
print(y_predict)

#I
y_predictInput = model.predict(x_test)
MSE = mean_squared_error(y_test, y_predictInput)
print(f"This is MSE value: {MSE}")

